### ISSUE TITLE
BYU 0.3.0 download shows as 0.20 in the BYUtv information screen

### ISSUE THREAD

**Issue by missjane63** [b-pass/plugin.video.byu-tv#2]
BYU 0.3.0 addon download shows as 0.2.0 when installed (in the BYUtv information screen in Kodi)

Kodi 20.2/Win 7/BYUtv 0.3.0 which shows as 0.2.0 in addon information screen

**Comment by b-pass** [comment]
Oop, thanks..  I will make sure the next one is correct (0.4.0)
