### ISSUE TITLE
Broken with Kodi 21(or BYUtv has updated their video apis)

### ISSUE THREAD

**Issue by AshitakaLax** [b-pass/plugin.video.byu-tv#3]
I realized that this app may not have received attention in a while.
So I'm not sure what the source of the issue.
It does handle all of the fan art/thumbnails great. It also fetched the latest episodes well. It just failed to play the videos.

I'm impressed by the app though.

**Comment by b-pass** [comment]
Thanks for reporting!

It was working for me w/kodi 21 a couple days ago.  I confirm it's not working right now.  Seems like their website is also not able to play video right now, so maybe just an outage on their side.

I will try it again in a few hours.

**Comment by b-pass** [comment]
Ok its working on the web for me now.  So I ought to be able to have the plugin working again tomorrow...

**Comment by b-pass** [comment]
Fix with releases 0.4.1.  Thanks!

**Comment by AshitakaLax** [comment]
Wow! I'm impressed I just barely got back to this. I'll try out the new plugin.
Thanks

**Comment by AshitakaLax** [comment]
I updated, but it turns out I didn't have widevinecdm.dll installed.
I went to the inputstreamhelper addon and manually reinstalled the latest widevinecdm and that fixed it.

Everything works great now!
My kids are going to love watching these, thanks.
